# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"-\n\x0bJoinRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\t\"J\n\x07Message\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0c\n\x04room\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"+\n\rStreamMessage\x12\x1a\n\x08messages\x18\x01 \x03(\x0b\x32\x08.Message\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2p\n\x0b\x43hatService\x12$\n\x04Join\x12\x0c.JoinRequest\x1a\x0e.StreamMessage\x12\x1f\n\x0bSendMessage\x12\x08.Message\x1a\x06.Empty\x12\x1a\n\tHeartbeat\x12\x05.User\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINREQUEST']._serialized_start=14
  _globals['_JOINREQUEST']._serialized_end=59
  _globals['_MESSAGE']._serialized_start=61
  _globals['_MESSAGE']._serialized_end=135
  _globals['_STREAMMESSAGE']._serialized_start=137
  _globals['_STREAMMESSAGE']._serialized_end=180
  _globals['_USER']._serialized_start=182
  _globals['_USER']._serialized_end=206
  _globals['_EMPTY']._serialized_start=208
  _globals['_EMPTY']._serialized_end=215
  _globals['_CHATSERVICE']._serialized_start=217
  _globals['_CHATSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
